/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xfast_ffmpegdemo_FFMpegTransformer */

#ifndef _Included_com_xfast_ffmpegdemo_FFMpegTransformer
#define _Included_com_xfast_ffmpegdemo_FFMpegTransformer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xfast_ffmpegdemo_FFMpegTransformer
 * Method:    pts
 * Signature: (Ljava/lang/String;Ljava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_com_xfast_ffmpegdemo_FFMpegTransformer_pts
  (JNIEnv *, jclass, jstring, jstring, jfloat);

/*
 * Class:     com_xfast_ffmpegdemo_FFMpegTransformer
 * Method:    overlay
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xfast_ffmpegdemo_FFMpegTransformer_overlay
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_xfast_ffmpegdemo_FFMpegTransformer
 * Method:    concat
 * Signature: ([Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xfast_ffmpegdemo_FFMpegTransformer_concat
  (JNIEnv *, jclass, jobjectArray, jstring);

/*
 * Class:     com_xfast_ffmpegdemo_FFMpegTransformer
 * Method:    gif
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xfast_ffmpegdemo_FFMpegTransformer_gif
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_xfast_ffmpegdemo_FFMpegTransformer
 * Method:    split
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xfast_ffmpegdemo_FFMpegTransformer_split
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
